service: wisaw

# Use serverless-webpack plugin to transpile ES6/ES7
plugins:
  - serverless-webpack
# Enable auto-packing of external modules
custom:
  webpackIncludeModules: true

provider:
  name: aws
  runtime: nodejs6.10
  memorySize: 128
  timeout: 30
  versionFunctions: false # optional, default is true
  environment:
    DATABASE_URL: ${file(.env.${opt:stage}.js):config.DATABASE_URL}
    HOST: ${file(.env.${opt:stage}.js):config.HOST}


functions:
  helloWorldRead: # just for testing purposes
    handler: api/src/controllers/hello_world.main
    description: greetings message for world
    events:
      - http:
          path: hello
          method: get
          private: false
  abuseReportCreate: # http endpoint
    handler: api/src/controllers/abuseReports/create.main
    description: create an abuse report record
    events:
      - http:
          path: /abusereport
          method: post
          private: false
  contactFormCreate: # http endpoint
    handler: api/src/controllers/contactForms/create.main
    description: create contact form record
    events:
      - http:
          path: /contactform
          method: post
          private: false
  photosCleanup: # http endpoint
    handler: api/src/controllers/photos/cleanupPhotos.main
    description: cleaning up old photos
    events:
      - http:
          path: photos/cleanup
          method: get
          private: false
  photosCleanupContinuously: # the same as above (reusing the same function), but is invoked by a scheduler
    handler: api/src/controllers/photos/cleanupPhotos.main
    description: cleaning up old photos periodically once an hour
    events:
      - schedule:
          rate: rate(1 hour)
          enabled: true
  photosCreate: # http endpoint
    handler: api/src/controllers/photos/create.main
    description: ('C'RUD) - photo
    memorySize: 300 # need to allocate more memory for Jimp image processing
    events:
      - http:
          path: /photos
          method: post
          private: false
  photosFeed: # http endpoint
    handler: api/src/controllers/photos/feed.main
    description: photos feed
    events:
      - http:
          path: /photos/feed
          method: post
          private: false
